### ISSUE TITLE
relative delta: 0 and 0 are not equal to within 0

### ISSUE THREAD

**Issue by kmx** [dagolden/Test-Number-Delta#2]
Hi again,

I am using: `use Test::Number::Delta relative => 0.001` 
and I have experienced this sort of failure: `0 and 0 are not equal to within 0`

The trouble occurs when comparing two `0.0` values

My suggestion is a patch like this:

```
--- Delta.pm.orig       2014-11-24 17:08:14.000000000 +0100
+++ Delta.pm    2014-11-25 12:21:14.707894000 +0100
@@ -184,7 +184,7 @@
         }
     }
     else {
-        $ok = abs( $p - $q ) < $epsilon;
+        $ok = abs( $p - $q ) < $epsilon || $p == $q;
         if ( !$ok ) {
             my ( $ep, $dp ) = _ep_dp($epsilon);
             $diag = sprintf( "%.${dp}f and %.${dp}f are not equal" . " to within %.${ep}f",
@@ -195,8 +195,8 @@
 }

 sub _ep_dp {
-    my $epsilon = shift
-      or return;
+    my $epsilon = shift;
+    return unless defined $epsilon;
     $epsilon = abs($epsilon);
     my ($exp) = sprintf( "%e", $epsilon ) =~ m/e(.+)/;
     my $ep = $exp < 0 ? -$exp : 1;
```

**Comment by dagolden** [comment]
That's kind of a interesting case, given the definition of relative.  I wonder if having the check be '<=' to epsilon would suffice.

Or, given your example, I wonder if comparing equality first actually makes more sense.  "If equal or within episilon, then consider them equal."
