### ISSUE TITLE
need doc clarity

### ISSUE THREAD

**Issue by tbrowder** [dagolden/Test-Number-Delta#3]
It is not clear to me what the effects are when mixing test functions and specifying a global relative tolerance.  

From reading the docs (not looking at the code), I believe the following statements are true:
1.  Setting a global value for epsilon affects only function "delta_ok."
2.  Function "delta_within" always takes an explicit epsilon which is always an absolute tolerance.

Confirmation or correction would be helpful.

Thanks for a very useful module!

**Comment by xdg** [comment]
That's correct, except the global value affects `delta_not_ok` as well.
